chrome_bin_location = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
webdriver_location = 'C:\chromedriver\chromedriver.exe'
url = 'https://passport.yandex.ru/auth'
password = 'gluman'
username = '260613'